# Generated by Django 5.2 on 2025-06-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chairs',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='chairs',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
