# Generated by Django 5.2 on 2025-06-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_chairs_options_chairs_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chairs',
            name='order',
        ),
    ]
