# Generated by Django 5.2 on 2025-06-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_chairs_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairs',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
