# Generated by Django 5.2 on 2025-06-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_chairs_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chairs',
            options={},
        ),
        migrations.RemoveField(
            model_name='chairs',
            name='category',
        ),
        migrations.RemoveField(
            model_name='chairs',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chairs',
            name='image',
        ),
        migrations.RemoveField(
            model_name='chairs',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chairs',
            name='order',
        ),
        migrations.RemoveField(
            model_name='chairs',
            name='price',
        ),
    ]
