# Generated by Django 5.2 on 2025-06-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_chairs_options_remove_chairs_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chairs',
            options={'ordering': ['category', 'order']},
        ),
        migrations.AddField(
            model_name='chairs',
            name='category',
            field=models.CharField(blank=True, choices=[('Most populer', 'MostPopuler'), ('HOMETOP', 'Home top')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chairs',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chairs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chairs'),
        ),
        migrations.AddField(
            model_name='chairs',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='chairs',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chairs',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
