# Generated by Django 5.2 on 2025-06-15 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_chairs_options_chairs_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chairs',
        ),
    ]
