# Generated by Django 5.2 on 2025-06-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0009_delete_chairs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chairs')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Most populer', 'MostPopuler'), ('HOMETOP', 'Home top')], max_length=50)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
    ]
