# Generated by Django 5.2 on 2025-06-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('phonenumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='chairs',
            name='category',
            field=models.CharField(choices=[('Most populer', 'MostPopuler'), ('HOMETOP', 'Home top'), ('HOMEBOTTOM', 'Home bottom'), ('OFFICECHAIRS', 'Office chairs'), ('INTERIOR', ' interior'), ('DIRECTORCHAIR', 'director_chair'), ('PREMIUM', 'Premium_chair'), ('WORKFORCE', 'Workforce_chair'), ('LOUNGE', 'Lounge_chair'), ('VISITOR', 'Visitor_chair'), ('CAFETERIA', 'Cafeteria_chair')], max_length=50),
        ),
    ]
