# Generated by Django 5.2 on 2025-07-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_cartmodel_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='quantity',
        ),
    ]
